import { ApiOrganizationOrganization } from "./ApiOrganizationOrganization";
import { ApiParentParent } from "./ApiParentParent";
import { ApiProvinceProvince } from "./ApiProvinceProvince";
import { ApiSchoolSchool } from "./ApiSchoolSchool";
import { ApiSubjectSubject } from "./ApiSubjectSubject";
import { ApiSupportDepartmentSupportDepartment } from "./ApiSupportDepartmentSupportDepartment";
import { ApiVoucherVoucher } from "./ApiVoucherVoucher";
import { PluginUploadFile } from "./PluginUploadFile";

export interface ApiProfileProfile {
  id: string;
  attributes: {
    about: string;
    addresses: string;
    banner: PluginUploadFile;
    cancelDate: string;
    createdAt: string;
    createdBy: string;
    darkMode: string;
    dob: string;
    documents: string;
    examNumber: string;
    firstName: string;
    gender: string;
    grades: string;
    hasSiyavulaAccess: string;
    idNumber: string;
    imei: string;
    inMailsBCC: string;
    inMailsCC: string;
    inMailsTos: string;
    isAffiliate: string;
    isDeveloper: string;
    isPaying: string;
    isPayingDate: string;
    lastName: string;
    locale: string;
    localizations: string;
    mobileNr: string;
    notifications: string;
    organization: ApiOrganizationOrganization;
    parents: ApiParentParent;
    profilePic: PluginUploadFile;
    progresses: string;
    provinces: ApiProvinceProvince;
    publishedAt: string;
    referral: string;
    schools: ApiSchoolSchool;
    serialNumber: string;
    shares: string;
    socialRead: string;
    subjects: ApiSubjectSubject;
    supportDepartments: ApiSupportDepartmentSupportDepartment;
    uniqueId: string;
    updatedAt: string;
    updatedBy: string;
    voucher: ApiVoucherVoucher;
  };
}
