packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  "@next/eslint-plugin-next": ^15.0.4
  autoprefixer: ^10.4.20
  eslint: ^9.9.0
  next: ^15.0.0
  postcss: ^8.4.41
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    "@types/node": ^22.10.1
  storybook:
    "@chromatic-com/storybook": 1.9.0
    "@storybook/addon-essentials": 8.3.6
    "@storybook/addon-interactions": 8.3.6
    "@storybook/addon-links": 8.3.6
    "@storybook/addon-themes": ^8.3.6
    "@storybook/blocks": 8.3.6
    "@storybook/react": 8.3.6
    "@storybook/react-vite": 8.3.6
    "@storybook/test": 8.3.6
    prop-types: 15.8.1
    storybook: 8.3.6
