packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  "@next/eslint-plugin-next": ^15.0.4
  autoprefixer: ^10.4.20
  eslint: ^9.17.0
  eslint-config-next: 15.0.4
  next: ^15.1.4
  postcss: ^8.4.41
  prettier: ^3.4.2
  tailwindcss: ^3.4.14
  typescript: ^5.7.2
  zod: ^3.24.1

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    "@types/node": ^22.10.1
  storybook:
    "@chromatic-com/storybook": ^3.2.3
    "@storybook/addon-essentials": 8.4.7
    "@storybook/addon-interactions": 8.4.7
    "@storybook/addon-links": 8.4.7
    "@storybook/addon-themes": 8.4.7
    "@storybook/blocks": 8.4.7
    "@storybook/react": 8.4.7
    "@storybook/react-vite": 8.4.7
    "@storybook/test": 8.4.7
    "@vitejs/plugin-react": ^4.3.4
    prop-types: 15.8.1
    storybook: 8.4.7
  api:
    "@apollo/client": 3.12.3
    "@strapi/strapi": 5.6.0
    axios: 1.7.9
    graphql: ^16.10.0
    graphql-tag: ^2.12.5
    openapi-typescript: 7.4.4
    openapi-fetch: ^0.13.3
    qs: ^6.13.1
    ts-morph: ^24.0.0
  ui:
    "@hookform/resolvers": ^3.9.1
    "@radix-ui/react-accordion": ^1.2.2
    "@radix-ui/react-alert-dialog": ^1.1.4
    "@radix-ui/react-avatar": ^1.1.2
    "@radix-ui/react-checkbox": ^1.1.3
    "@radix-ui/react-collapsible": ^1.1.2
    "@radix-ui/react-dialog": ^1.1.4
    "@radix-ui/react-dropdown-menu": ^2.1.4
    "@radix-ui/react-icons": ^1.3.2
    "@radix-ui/react-label": ^2.1.1
    "@radix-ui/react-popover": ^1.1.4
    "@radix-ui/react-progress": ^1.1.1
    "@radix-ui/react-radio-group": ^1.2.2
    "@radix-ui/react-scroll-area": ^1.2.2
    "@radix-ui/react-select": ^2.1.2
    "@radix-ui/react-separator": ^1.1.1
    "@radix-ui/react-slider": ^1.2.2
    "@radix-ui/react-slot": ^1.1.1
    "@radix-ui/react-switch": ^1.1.2
    "@radix-ui/react-tabs": ^1.1.2
    "@radix-ui/react-toast": ^1.2.4
    "@radix-ui/react-tooltip": ^1.1.6
    "@tanstack/react-table": ^8.20.6
    class-variance-authority: ^0.7.1
    cmdk: 1.0.4
    date-fns: ^4.1.0
    framer-motion: ^11.15.0
    fuse.js: ^7.0.0
    input-otp: ^1.4.1
    lucide-react: ^0.468.0
    next-themes: ^0.4.4
    quill: ^2.0.3
    react-day-picker: ^9.4.4
    react-draggable: ^4.4.5
    react-dropzone: ^14.3.5
    react-hook-form: ^7.54.1
    react-pdf: ^9.1.1
    react-player: ^2.16.0
    react-quill: ^2.0.0
    react-resizable-panels: ^2.1.7
    react-router-dom: ^6.28.0
    react-markdown: ^9.0.1
    react-multiline-clamp: ^2.0.0
    recharts: ^2.15.0
    remark-gfm: ^4.0.0
    remeda: "2"
    shiki: ^1.26.1
    sonner: ^1.7.1
    tailwind-merge: ^2.5.5
    vaul: ^1.1.2
    web-push: ^3.6.7
  jest:
    "@testing-library/react": 16.1.0
    "@testing-library/user-event": ^14.5.2
    "@types/jest": ^29.5.13
    "@types/react-test-renderer": ^19.0.0
    jest: ^29.7.0
    jest-environment-jsdom: ^29.7.0
    jest-expo: ^52.0.2
    react-test-renderer: ^19.0.0
    ts-jest: ^29.2.5
