packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  "@next/eslint-plugin-next": ^15.0.4
  autoprefixer: ^10.4.20
  eslint: ^9.9.0
  eslint-config-next: 15.0.4
  next: ^15.1.0
  postcss: ^8.4.41
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    "@types/node": ^22.10.1
  storybook:
    "@chromatic-com/storybook": 1.9.0
    "@storybook/addon-essentials": 8.4.7
    "@storybook/addon-interactions": 8.4.7
    "@storybook/addon-links": 8.4.7
    "@storybook/addon-themes": 8.4.7
    "@storybook/blocks": 8.4.7
    "@storybook/react": 8.4.7
    "@storybook/react-vite": 8.4.7
    "@storybook/test": 8.4.7
    prop-types: 15.8.1
    storybook: 8.4.7
  api:
    "@apollo/client": 3.12.2
    axios: 1.7.9
    openapi-typescript: 7.4.4
    graphql: ^16.9.0
  ui:
    "@hookform/resolvers": ^3.9.0
    "@radix-ui/react-accordion": ^1.2.1
    "@radix-ui/react-avatar": ^1.1.1
    "@radix-ui/react-checkbox": ^1.1.2
    "@radix-ui/react-collapsible": ^1.1.1
    "@radix-ui/react-dialog": ^1.1.2
    "@radix-ui/react-dropdown-menu": ^2.1.2
    "@radix-ui/react-icons": ^1.3.2
    "@radix-ui/react-label": ^2.1.0
    "@radix-ui/react-popover": ^1.1.2
    "@radix-ui/react-progress": ^1.1.0
    "@radix-ui/react-radio-group": ^1.2.1
    "@radix-ui/react-scroll-area": ^1.2.0
    "@radix-ui/react-select": ^2.1.2
    "@radix-ui/react-separator": ^1.1.0
    "@radix-ui/react-slider": ^1.2.1
    "@radix-ui/react-slot": ^1.1.0
    "@radix-ui/react-switch": ^1.1.1
    "@radix-ui/react-tabs": ^1.1.1
    "@radix-ui/react-toast": ^1.2.2
    "@radix-ui/react-tooltip": ^1.1.3
    "@tanstack/react-table": ^8.20.5
    class-variance-authority: ^0.7.0
    cmdk: 1.0.4
    date-fns: ^4.1.0
    framer-motion: ^11.13.5
    fuse.js: ^6.5.3
    input-otp: ^1.4.1
    lucide-react: ^0.453.0
    next-themes: ^0.4.4
    quill: ^2.0.2
    react-day-picker: ^9.4.2
    react-draggable: ^4.4.5
    react-dropzone: ^11.4.2
    react-hook-form: ^7.52.2
    react-pdf: ^9.1.1
    react-player: ^2.16.0
    react-quill: ^2.0.0
    react-resizable-panels: ^2.1.5
    react-router-dom: ^6.28.0
    recharts: ^2.14.1
    sonner: ^1.7.1
    tailwind-merge: ^2.5.2
    vaul: ^1.1.1
    web-push: ^3.6.7
  jest:
    "@testing-library/react": 16.1.0
    "@testing-library/user-event": ^14.5.2
    "@types/jest": ^29.5.13
    "@types/react-test-renderer": ^19.0.0
    jest: ^29.7.0
    jest-environment-jsdom: ^29.7.0
    jest-expo: ^52.0.2
    react-test-renderer: ^19.0.0
    ts-jest: ^29.2.5
