import type { Metadata } from "next";
import React from "react";
import { BrowserRouter } from "react-router-dom";

import { TimeTrackerProvider } from "@acme/snippets";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <BrowserRouter>
        <TimeTrackerProvider>
          <body className={`antialiased`}>{children}</body>
        </TimeTrackerProvider>
      </BrowserRouter>
    </html>
  );
}
